Repository vectorwing/FarmersDelight, pull requests merged in 2023-07, with the labels that each got.

#756 Updating russian localization for 1.18.2
  src/main/resources/assets/farmersdelight/lang/ru_ru.json
Labels: translation

#719 added tag compat for create crafts and additions
  src/generated/resources/.cache/cache
  src/generated/resources/data/createaddition/tags/items/plant_foods.json
  src/generated/resources/data/createaddition/tags/items/plants.json
  src/main/java/vectorwing/farmersdelight/common/tag/CompatibilityTags.java
  src/main/java/vectorwing/farmersdelight/data/ItemTags.java
Labels: integration

#727 Added some translation to Spanish language
  src/main/resources/assets/farmersdelight/lang/es_es.json
Labels: translation

#635 Fix Create's Harvester not consuming Tomato Seeds when replanting
  src/main/java/vectorwing/farmersdelight/common/registry/ModItems.java
Labels: bug, integration

#764 Update ko_kr.json
  src/main/resources/assets/farmersdelight/lang/ko_kr.json
Labels: translation
